version: '3.9'
services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 4000
      REDIS_URL: redis://redis:6379
      RESET_ON_START: 1
      SALE_TOTAL_STOCK: 1000
    ports:
      - "4000:4000"
    depends_on:
      - redis
    volumes:
      - ./apps/api:/app
      - /app/node_modules

  web:
    working_dir: /app
    image: node:20-alpine
    command: sh -c "corepack enable && corepack prepare pnpm@9.0.0 --activate && pnpm i && pnpm --filter @flash-sale/web dev --host 0.0.0.0"
    environment:
      VITE_API_URL: http://localhost:4000
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

networks:
  default:
    name: flash-sale
